### ISSUE TITLE
KeyError: 'SEGFORMER_PATH'

### ISSUE THREAD

**Issue by JerryX1110** [ashutosh1807/Depthformer#1]
Traceback (most recent call last):
  File "train.py", line 407, in <module>
    mp.spawn(main_worker, nprocs=ngpus_per_node, args=(ngpus_per_node, args))
  File "/mnt/cache/xuxiaohao/miniconda3/envs/monodep/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 199, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/mnt/cache/xuxiaohao/miniconda3/envs/monodep/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 157, in start_processes
    while not context.join():
  File "/mnt/cache/xuxiaohao/miniconda3/envs/monodep/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception:

-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File "/mnt/cache/xuxiaohao/miniconda3/envs/monodep/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/mnt/lustrenew/xuxiaohao/Depthformer-main/train.py", line 74, in main_worker
    norm=args.norm)
  File "/mnt/lustrenew/xuxiaohao/Depthformer-main/models/unet_adaptive_bins.py", line 159, in build
    state_dict = torch.load(os.environ['SEGFORMER_PATH'])
  File "/mnt/cache/xuxiaohao/miniconda3/envs/monodep/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'SEGFORMER_PATH'

**Comment by ashutosh1807** [comment]
You can set the path for the pretrained model using
`export SEGFORMER_PATH='mit_b4.pt`

**Comment by JerryX1110** [comment]
Thanks for your timely reply and elegant work! : )

**Comment by Arunsuchi** [comment]
export SEGFORMER_PATH='mit_b4.pt

How to do this? Pls suggest. I am also facing same problem with above issue.  Ashutosh pls help. I am struggling from long time
